version: '3'

services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diet_detective
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./DietDetectiveSpring/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/diet_detective
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  frontend:
    container_name: frontend
    build:
      context: ./DietDetectiveReact/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    expose:
      - "3000"

volumes:
  db:
    driver: local